/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_vediodecoder_NativeMethod */

#ifndef _Included_com_example_vediodecoder_NativeMethod
#define _Included_com_example_vediodecoder_NativeMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_vediodecoder_NativeMethod
 * Method:    createInstance
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_example_vediodecoder_NativeMethod_createInstance
  (JNIEnv *, jclass, jstring, jint, jlong);

/*
 * Class:     com_example_vediodecoder_NativeMethod
 * Method:    initMediaCodec
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_vediodecoder_NativeMethod_initMediaCodec
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_example_vediodecoder_NativeMethod
 * Method:    startPlay
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_vediodecoder_NativeMethod_startPlay
  (JNIEnv *, jclass, jlong, jint, jint, jobject);

/*
 * Class:     com_example_vediodecoder_NativeMethod
 * Method:    stopPlay
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_vediodecoder_NativeMethod_stopPlay
  (JNIEnv *, jclass, jlong);

JNIEXPORT jint JNI_OnLoad(JavaVM* vm, void* reserved);

#ifdef __cplusplus
}
#endif
#endif
